export function getBetexplorerUrl(country, league) {
  const map = {
    "Albania:Kategoria Superiore": "/soccer/albania/super-league/",
    "Algeria:Ligue Professionnelle 1": "/soccer/algeria/ligue-1/",
    "Argentina:Primera División": "/soccer/argentina/primera-division/",
    "Argentina:Primera Nacional": "/soccer/argentina/primera-nacional/",
    "Armenia:Armenian Premier League": "/soccer/armenia/premier-league/",
    "Australia:A-League Men": "/soccer/australia/a-league/",
    "Australia:A-League Women": "/soccer/australia/w-league/",
    "Austria:Austrian Bundesliga": "/soccer/austria/bundesliga/",
    "Austria:2. Liga": "/soccer/austria/2-liga/",
    "Azerbaijan:Azerbaijan Premier League": "/soccer/azerbaijan/premier-league/",
    "Belarus:Belarusian Premier League": "/soccer/belarus/premier-league/",
    "Belgium:Pro League": "/soccer/belgium/jupiler-league/",
    "Belgium:Challenger Pro League": "/soccer/belgium/proximus-league/",
    "Bolivia:División Profesional": "/soccer/bolivia/liga-profesional/",
    "Bosnia and Herzegovina:Premier League of Bosnia and Herzegovina": "/soccer/bosnia-herzegovina/premier-league/",
    "Brazil:Campeonato Brasileiro Série A": "/soccer/brazil/serie-a/",
    "Brazil:Campeonato Brasileiro Série B": "/soccer/brazil/serie-b/",
    "Bulgaria:First Professional Football League": "/soccer/bulgaria/parva-liga/",
    "Cameroon:Elite One": "/soccer/cameroon/elite-one/",
    "Chile:Primera División": "/soccer/chile/primera-division/",
    "Chile:Primera B": "/soccer/chile/primera-b/",
    "China:Chinese Super League": "/soccer/china/super-league/",
    "China:China League One": "/soccer/china/league-1/",
    "Colombia:Categoría Primera A": "/soccer/colombia/liga-aguila/",
    "Colombia:Categoría Primera B": "/soccer/colombia/primera-b/",
    "Croatia:Croatian First Football League": "/soccer/croatia/1-hnl/",
    "Cyprus:Cypriot First Division": "/soccer/cyprus/first-division/",
    "Czechia (Czech Republic):Czech First League": "/soccer/czech-republic/1-liga/",
    "Democratic Republic of the Congo:Linafoot": "/soccer/congo/linafoot/",
    "Denmark:Danish Superliga": "/soccer/denmark/superliga/",
    "Denmark:1st Division": "/soccer/denmark/1st-division/",
    "Ecuador:Serie A": "/soccer/ecuador/serie-a/",
    "Ecuador:Serie B": "/soccer/ecuador/serie-b/",
    "Egypt:Egyptian Premier League": "/soccer/egypt/premier-league/",
    "Estonia:Meistriliiga": "/soccer/estonia/meistriliiga/",
    "Finland:Veikkausliiga": "/soccer/finland/veikkausliiga/",
    "Finland:Ykkönen": "/soccer/finland/ykkonen/",
    "France:Ligue 1": "/soccer/france/ligue-1/",
    "France:Ligue 2": "/soccer/france/ligue-2/",
    "Georgia:Erovnuli Liga": "/soccer/georgia/erovnuli-liga/",
    "Germany:Bundesliga": "/soccer/germany/bundesliga/",
    "Germany:2. Bundesliga": "/soccer/germany/2-bundesliga/",
    "Germany:3. Liga": "/soccer/germany/3-liga/",
    "Ghana:Ghana Premier League": "/soccer/ghana/premier-league/",
    "Greece:Super League Greece": "/soccer/greece/super-league/",
    "Greece:Super League 2": "/soccer/greece/super-league-2/",
    "Hungary:Nemzeti Bajnokság I": "/soccer/hungary/nb-i/",
    "Hungary:Nemzeti Bajnokság II": "/soccer/hungary/nb-ii/",
    "Iceland:Úrvalsdeild karla": "/soccer/iceland/urvalsdeild/",
    "Iceland:1. deild karla": "/soccer/iceland/1-deild/",
    "India:Indian Super League": "/soccer/india/super-league/",
    "India:I-League": "/soccer/india/i-league/",
    "Indonesia:Liga 1": "/soccer/indonesia/liga-1/",
    "Indonesia:Liga 2": "/soccer/indonesia/liga-2/",
    "Iran:Persian Gulf Pro League": "/soccer/iran/persian-gulf-league/",
    "Iraq:Iraqi Premier League": "/soccer/iraq/premier-league/",
    "Ireland:League of Ireland Premier Division": "/soccer/ireland/premier-division/",
    "Ireland:First Division": "/soccer/ireland/first-division/",
    "Israel:Israeli Premier League": "/soccer/israel/ligat-haal/",
    "Israel:Liga Leumit": "/soccer/israel/liga-leumit/",
    "Italy:Serie A": "/soccer/italy/serie-a/",
    "Italy:Serie B": "/soccer/italy/serie-b/",
    "Italy:Serie C": "/soccer/italy/serie-c/",
    "Japan:J1 League": "/soccer/japan/j-league/",
    "Japan:J2 League": "/soccer/japan/j-league-2/",
    "Japan:J3 League": "/soccer/japan/j-league-3/",
    "Jordan:Jordanian Pro League": "/soccer/jordan/pro-league/",
    "Kazakhstan:Kazakhstan Premier League": "/soccer/kazakhstan/premier-league/",
    "Kenya:Kenyan Premier League": "/soccer/kenya/premier-league/",
    "Latvia:Virslīga": "/soccer/latvia/virsliga/",
    "Lebanon:Lebanese Premier League": "/soccer/lebanon/premier-league/",
    "Lesotho:Lesotho Premier League": "/soccer/lesotho/premier-league/",
    "Liberia:Liberian First Division League": "/soccer/liberia/first-division/",
    "Libya:Libyan Premier League": "/soccer/libya/premier-league/",
    "Lithuania:A Lyga": "/soccer/lithuania/a-lyga/",
    "Luxembourg:National Division": "/soccer/luxembourg/national-division/",
    "Madagascar:Malagasy Pro League": "/soccer/madagascar/pro-league/",
    "Malawi:Super League of Malawi": "/soccer/malawi/super-league/",
    "Malaysia:Malaysia Super League": "/soccer/malaysia/super-league/",
    "Mali:Malian Première Division": "/soccer/mali/premiere-division/",
    "Malta:Maltese Premier League": "/soccer/malta/premier-league/",
    "Mauritania:Super D1": "/soccer/mauritania/super-d1/",
    "Mauritius:Mauritian Premier League": "/soccer/mauritius/premier-league/",
    "Mexico:Liga MX": "/soccer/mexico/liga-mx/",
    "Mexico:Liga de Expansión MX": "/soccer/mexico/expansion-mx/",
    "Moldova:Moldovan National Division": "/soccer/moldova/national-division/",
    "Morocco:Botola Pro": "/soccer/morocco/botola-pro/",
    "Mozambique:Moçambola": "/soccer/mozambique/mocambola/",
    "Netherlands:Eredivisie": "/soccer/netherlands/eredivisie/",
    "Netherlands:Eerste Divisie": "/soccer/netherlands/eerste-divisie/",
    "Nigeria:Nigeria Professional Football League": "/soccer/nigeria/professional-league/",
    "Norway:Eliteserien": "/soccer/norway/eliteserien/",
    "Norway:1. divisjon": "/soccer/norway/1-division/",
    "Oman:Oman Professional League": "/soccer/oman/professional-league/",
    "Pakistan:Pakistan Premier League": "/soccer/pakistan/premier-league/",
    "Palestine State:Palestine Premier League": "/soccer/palestine/premier-league/",
    "Panama:Liga Panameña de Fútbol": "/soccer/panama/liga-panama/",
    "Paraguay:Primera División": "/soccer/paraguay/primera-division/",
    "Peru:Liga 1": "/soccer/peru/liga-1/",
    "Philippines:Philippine Football League": "/soccer/philippines/football-league/",
    "Poland:Ekstraklasa": "/soccer/poland/ekstraklasa/",
    "Poland:I liga": "/soccer/poland/i-liga/",
    "Portugal:Primeira Liga": "/soccer/portugal/primeira-liga/",
    "Portugal:Liga Portugal 2": "/soccer/portugal/liga-portugal-2/",
    "Qatar:Qatar Stars League": "/soccer/qatar/stars-league/",
    "Romania:Liga I": "/soccer/romania/liga-i/",
    "Russia:Russian Premier League": "/soccer/russia/premier-league/",
    "Russia:Russian First League": "/soccer/russia/first-league/",
    "Rwanda:Rwanda National Football League": "/soccer/rwanda/national-league/",
    "Saudi Arabia:Saudi Professional League": "/soccer/saudi-arabia/professional-league/",
    "Senegal:Ligue 1 (Senegal)": "/soccer/senegal/ligue-1/",
    "Serbia:Serbian SuperLiga": "/soccer/serbia/super-liga/",
    "Serbia:Serbian First League": "/soccer/serbia/prva-liga/",
    "Singapore:Singapore Premier League": "/soccer/singapore/premier-league/",
    "Slovakia:Slovak Super Liga": "/soccer/slovakia/super-liga/",
    "Slovenia:Slovenian PrvaLiga": "/soccer/slovenia/prva-liga/",
    "South Africa:Premier Soccer League": "/soccer/south-africa/premier-league/",
    "South Korea:K League 1": "/soccer/south-korea/k-league-1/",
    "South Korea:K League 2": "/soccer/south-korea/k-league-2/",
    "Spain:La Liga": "/soccer/spain/laliga/",
    "Spain:Segunda División": "/soccer/spain/segunda-division/",
    "Sweden:Allsvenskan": "/soccer/sweden/allsvenskan/",
    "Sweden:Superettan": "/soccer/sweden/superettan/",
    "Switzerland:Swiss Super League": "/soccer/switzerland/super-league/",
    "Switzerland:Challenge League": "/soccer/switzerland/challenge-league/",
    "Tanzania:Tanzanian Premier League": "/soccer/tanzania/premier-league/",
    "Thailand:Thai League 1": "/soccer/thailand/league-1/",
    "Thailand:Thai League 2": "/soccer/thailand/league-2/",
    "Tunisia:Tunisian Ligue Professionnelle 1": "/soccer/tunisia/ligue-1/",
    "Turkey:Süper Lig": "/soccer/turkey/super-lig/",
    "Turkey:TFF First League": "/soccer/turkey/1-lig/",
    "Uganda:Ugandan Premier League": "/soccer/uganda/premier-league/",
    "Ukraine:Ukrainian Premier League": "/soccer/ukraine/premier-league/",
    "Ukraine:Ukrainian First League": "/soccer/ukraine/first-league/",
    "United Arab Emirates:UAE Pro League": "/soccer/uae/pro-league/",
    "United Kingdom:Premier League": "/soccer/england/premier-league/",
    "United Kingdom:Championship": "/soccer/england/championship/",
    "United Kingdom:League One": "/soccer/england/league-one/",
    "United Kingdom:League Two": "/soccer/england/league-two/",
    "United States:Major League Soccer": "/soccer/usa/mls/",
    "United States:USL Championship": "/soccer/usa/usl-championship/",
    "Uruguay:Primera División": "/soccer/uruguay/primera-division/",
    "Uruguay:Segunda División": "/soccer/uruguay/segunda-division/",
    "Uzbekistan:Uzbekistan Super League": "/soccer/uzbekistan/super-league/",
    "Venezuela:Venezuelan Primera División": "/soccer/venezuela/primera-division/",
    "Vietnam:V.League 1": "/soccer/vietnam/v-league-1/",
    "Vietnam:V.League 2": "/soccer/vietnam/v-league-2/",
    "Yemen:Yemeni League": "/soccer/yemen/yemeni-league/",
    "Zambia:Zambia Super League": "/soccer/zambia/super-league/",
    "Zimbabwe:Zimbabwe Premier Soccer League": "/soccer/zimbabwe/premier-league/"
  };
  return map[`${country}:${league}`] || "";
}
